"""HTML report generator — full dashboard with scorecard, gradients, gamut."""

from __future__ import annotations

import json
import math
from pathlib import Path


def generate_report(eval_result, name: str, output_path: str = "report.html",
                    comparison=None) -> str:
    """Generate HTML dashboard report.

    Args:
        eval_result: Raw evaluation results dict or Comparison object
        name: Space name
        output_path: Output HTML file path
        comparison: Optional Comparison object for multi-space view

    Returns:
        Path to generated HTML file.
    """
    # Handle both raw results and Comparison objects
    if hasattr(eval_result, "tests"):
        # It's a Comparison
        html = _generate_comparison_html(eval_result, name)
    else:
        html = _generate_single_html(eval_result, name)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(html)

    return output_path


def _generate_single_html(results: dict, name: str) -> str:
    """Generate HTML for single-space evaluation."""
    try:
        from ..metrics.registry import _get_colorbench_modules
        _, _, _, _, comparison_mod, _ = _get_colorbench_modules()
        metric_defs = comparison_mod.METRIC_DEFS
    except ImportError:
        metric_defs = []

    # Extract scores
    scores = {}
    for mdef in metric_defs:
        score = comparison_mod._extract_score(results, mdef.result_key, mdef.score_path)
        if score is not None:
            scores[mdef.name] = {
                "value": score,
                "category": mdef.category,
                "unit": mdef.unit,
                "lower_is_better": mdef.lower_is_better,
            }

    # Group by category
    categories = {}
    for mname, data in scores.items():
        cat = data["category"]
        if cat not in categories:
            categories[cat] = []
        categories[cat].append((mname, data))

    # Build HTML
    rows = []
    for cat, metrics in categories.items():
        rows.append(f'<tr><td colspan="3" class="cat-header">{cat}</td></tr>')
        for mname, data in metrics:
            val = data["value"]
            unit = data["unit"]
            fmt = f"{val:.4f}" if abs(val) < 1000 else f"{val:.2e}"
            rows.append(f'<tr><td>{mname}</td><td class="score">{fmt}</td>'
                        f'<td class="unit">{unit}</td></tr>')

    scorecard_html = "\n".join(rows)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SpaceForge Report — {name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 900px; margin: 40px auto; padding: 0 20px; background: #0d1117; color: #e6edf3; }}
h1 {{ color: #58a6ff; }}
h2 {{ color: #79c0ff; border-bottom: 1px solid #30363d; padding-bottom: 8px; }}
table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
td, th {{ padding: 6px 12px; text-align: left; border-bottom: 1px solid #21262d; }}
.cat-header {{ font-weight: bold; background: #161b22; color: #8b949e; font-size: 0.85em;
               text-transform: uppercase; letter-spacing: 1px; padding: 10px 12px; }}
.score {{ font-family: 'SF Mono', monospace; text-align: right; color: #7ee787; }}
.unit {{ color: #8b949e; font-size: 0.85em; }}
.meta {{ color: #8b949e; font-size: 0.9em; margin-bottom: 24px; }}
</style>
</head>
<body>
<h1>SpaceForge Report</h1>
<div class="meta">
  Space: <strong>{name}</strong>
</div>

<h2>Scorecard ({len(scores)} metrics)</h2>
<table>
<tr><th>Metric</th><th>Score</th><th>Unit</th></tr>
{scorecard_html}
</table>

<p style="color: #8b949e; font-size: 0.8em;">
  Generated by SpaceForge v0.1.0 — Color Space Development Engine
</p>
</body>
</html>"""


def _generate_comparison_html(comparison, name: str) -> str:
    """Generate HTML for multi-space comparison."""
    space_names = comparison.space_names
    n_spaces = len(space_names)

    # Header row
    header_cols = "".join(f"<th>{s}</th>" for s in space_names)

    # Metric rows
    rows = []
    current_cat = ""
    for tr in comparison.tests:
        cat = tr.metric.category
        if cat != current_cat:
            rows.append(f'<tr><td colspan="{n_spaces + 2}" class="cat-header">{cat}</td></tr>')
            current_cat = cat

        cells = []
        for s in space_names:
            score = tr.scores.get(s)
            if score is None:
                cells.append('<td class="score na">N/A</td>')
            else:
                is_winner = (tr.winner == s) if tr.winner else False
                is_ref = s in tr.ref_spaces
                cls = "winner" if is_winner else ("ref" if is_ref else "score")

                fmt = tr.metric.format_str or ".4f"
                if fmt == "d":
                    val_str = str(int(score))
                elif fmt == ".2e":
                    val_str = f"{score:.2e}"
                else:
                    val_str = f"{score:{fmt}}"

                cells.append(f'<td class="{cls}">{val_str}</td>')

        winner_str = tr.winner or ("TIE" if tr.is_tie else "?")
        ref_str = f' <span class="ref-tag">(ref)</span>' if tr.ref_spaces else ""
        cells_html = "".join(cells)
        rows.append(f'<tr><td>{tr.metric.name}</td>{cells_html}'
                    f'<td class="winner-col">{winner_str}{ref_str}</td></tr>')

    table_html = "\n".join(rows)

    # Win summary
    win_rows = []
    for s in space_names:
        win_rows.append(f"<tr><td>{s}</td><td>{comparison.solo_wins[s]}</td>"
                        f"<td>{comparison.shared_wins[s]}</td></tr>")
    wins_html = "\n".join(win_rows)

    # Head-to-head
    h2h_rows = []
    for (s1, s2), h in comparison.head_to_head.items():
        h2h_rows.append(f"<tr><td>{s1} vs {s2}</td>"
                        f"<td>{h['w1']}-{h['w2']}</td><td>{h['tie']} ties</td></tr>")
    h2h_html = "\n".join(h2h_rows)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SpaceForge Comparison — {name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       max-width: 1200px; margin: 40px auto; padding: 0 20px; background: #0d1117; color: #e6edf3; }}
h1 {{ color: #58a6ff; }}
h2 {{ color: #79c0ff; border-bottom: 1px solid #30363d; padding-bottom: 8px; }}
table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
td, th {{ padding: 6px 12px; text-align: left; border-bottom: 1px solid #21262d; }}
.cat-header {{ font-weight: bold; background: #161b22; color: #8b949e; font-size: 0.85em;
               text-transform: uppercase; letter-spacing: 1px; }}
.score {{ font-family: 'SF Mono', monospace; text-align: right; }}
.winner {{ font-family: 'SF Mono', monospace; text-align: right; color: #7ee787; font-weight: bold; }}
.ref {{ font-family: 'SF Mono', monospace; text-align: right; color: #8b949e; font-style: italic; }}
.na {{ color: #484f58; }}
.winner-col {{ color: #d2a8ff; font-size: 0.85em; }}
.ref-tag {{ color: #f85149; font-size: 0.75em; }}
.summary {{ display: flex; gap: 40px; margin: 24px 0; }}
.summary table {{ width: auto; }}
</style>
</head>
<body>
<h1>SpaceForge Comparison</h1>

<div class="summary">
<div>
<h2>Wins</h2>
<table>
<tr><th>Space</th><th>Solo</th><th>Shared</th></tr>
{wins_html}
</table>
</div>
<div>
<h2>Head-to-Head</h2>
<table>
<tr><th>Matchup</th><th>Score</th><th>Ties</th></tr>
{h2h_html}
</table>
</div>
</div>

<h2>Full Scorecard ({len(comparison.tests)} metrics)</h2>
<table>
<tr><th>Metric</th>{header_cols}<th>Winner</th></tr>
{table_html}
</table>

<p style="color: #8b949e; font-size: 0.8em;">
  Generated by SpaceForge v0.1.0 — Color Space Development Engine
</p>
</body>
</html>"""


def generate_sensitivity_heatmap(sensitivity_result: dict,
                                 output_path: str = "sensitivity.html") -> str:
    """Generate HTML heatmap for sensitivity analysis."""
    metric_names = sensitivity_result["metric_names"]
    param_labels = sensitivity_result["param_labels"]
    J = sensitivity_result["jacobian"]

    # Normalize for color scaling
    max_val = max(abs(J[i][j]) for i in range(len(J)) for j in range(len(J[0])))
    if max_val < 1e-30:
        max_val = 1.0

    # Build heatmap cells
    rows = []
    for i, m_name in enumerate(metric_names):
        cells = []
        for j in range(len(param_labels)):
            val = J[i][j]
            intensity = min(abs(val) / max_val, 1.0)
            if val > 0:
                color = f"rgba(126, 231, 135, {intensity})"  # green
            else:
                color = f"rgba(248, 81, 73, {intensity})"  # red
            cells.append(f'<td style="background: {color}" title="{val:+.4f}">'
                         f'{val:+.3f}</td>')

        cells_html = "".join(cells)
        rows.append(f'<tr><td class="metric-label">{m_name}</td>{cells_html}</tr>')

    rows_html = "\n".join(rows)
    header_cols = "".join(f'<th class="param-label">{p}</th>' for p in param_labels)

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Sensitivity Heatmap</title>
<style>
body {{ font-family: monospace; background: #0d1117; color: #e6edf3; padding: 20px; }}
table {{ border-collapse: collapse; font-size: 11px; }}
td, th {{ padding: 3px 6px; border: 1px solid #21262d; text-align: right; }}
.metric-label {{ text-align: left; color: #8b949e; min-width: 200px; }}
.param-label {{ writing-mode: vertical-rl; transform: rotate(180deg); font-size: 10px; }}
h1 {{ color: #58a6ff; }}
</style></head>
<body>
<h1>Parameter Sensitivity Heatmap</h1>
<table>
<tr><th></th>{header_cols}</tr>
{rows_html}
</table>
</body></html>"""

    with open(output_path, "w") as f:
        f.write(html)

    return output_path
